services:
  qdrant:
    image: qdrant/qdrant:v1.6.1
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - ./qdrant_data:/qdrant_data


